/*
 * This source file was generated by the Gradle 'init' task
 */
package dsa;

import java.util.logging.Logger;

public class App {
    static Logger log = Logger.getLogger(App.class.getName());
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        log.info(new App().getGreeting());
    }
}
